version: "3"
services:
  fake_rest:
    image: jaxgeller/lwan
    volumes:
      - ./data:/lwan/wwwroot
    ports:
      - "8000:8080"
  fake_graphql:
    build:
      context: ./graphql-server
    ports:
      - "4000:4000"
  krakend_ce:
    image: devopsfaith/krakend:1.3.0
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "8080:8080"
    depends_on:
      - fake_rest
      - fake_graphql
